### ISSUE TITLE
sign invalid

### ISSUE THREAD

**Issue by Mikiiw** [tuya/tuya-android-industry-app-sdk-sample#11]
I'm trying to develop a way to connect to my smart plug via android SDK but I'm struggling to get past the signing process. Any invalid access id gives me an ip block but the android sdk client id and secret gives me this:

```
RequestTask onResponse body: {"code":1004,"msg":"sign invalid","success":false,"t":1657718894856,"tid":"a625198b02af11ed88959287a6a8350d"}
 (31109): RequestTask errorCode: 1004 errorMessage: sign invalid
```

I've not been able to continue part this part. Is there any advice so I can move forward with this process?

**Comment by radishwu** [comment]
Have you tried this way, like this https://developer.tuya.com/en/docs/app-development/preparation?id=Ka69nt983bhh5#title-1-Procedure.

**Comment by Mikiiw** [comment]
Your readme uses everything from the cloud development platform and not via the app platform. Unfortunately I did not follow this doc to get the SDK working

**Comment by Mikiiw** [comment]
Your readme uses everything from the cloud development platform and not via the app platform. Unfortunately I did not follow this doc to get the SDK working

**Comment by Mikiiw** [comment]
![chrome_uNMTscg9Kw](https://user-images.githubusercontent.com/32526912/178986942-66f60124-4954-4ae0-8f5c-d876b057260a.png)

I've used the endpoint from the api explorer to see if I'm able to login using the cloud auth. I can successfully generate a token this way

![chrome_HedXwwSsR7](https://user-images.githubusercontent.com/32526912/178988380-d30d2123-48f8-44eb-bf1e-abd6d5515a5f.png)

This is the expected output I should get from the API. However I'm not, I'm receiving an 'invalid signing response'. I would appreciate any response to what I've found

**Comment by radishwu** [comment]
Did you add SHA256 hash value? Android SDK need this. see https://developer.tuya.com/en/docs/app-development/iot_app_sdk_core_sha1?id=Kao7c7b139vrh. and 
![image](https://user-images.githubusercontent.com/11703563/179132525-4325be43-e0f2-438c-8790-62e6811ed79f.png)

**Comment by radishwu** [comment]
If still wrong, we suggest you move here to ask your question: https://service.console.tuya.com/8/3/create?step=4&id=01030408&source=suspension,to provide you with one-on-one guidance to match.

**Comment by Mikiiw** [comment]
![chrome_TmFqlq4QGj](https://user-images.githubusercontent.com/32526912/179202364-7b06fb02-d746-468a-8879-50e9dce6c261.png)

This is the wrong information. I've been asking for any advice on using this Industry App SDK. The information given here is for the Smart Life App configuration.

**Comment by radishwu** [comment]
Please check this [doc](https://developer.tuya.com/en/docs/app-development/iot-app-sdsk-core-preparation?id=Kaq9m1mhc5phr) .
